spring:
  application:
    name: patient-service
#  datasource:
#    url: jdbc:postgresql://postgres:5432/patient_service_db
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
server:
  port: 8000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
logging:
  level:
    com.pms.patientservice: DEBUG
    org.springframework.web: DEBUG